services:
  postgres:
    image: postgres:16-alpine
    container_name: spc-postgres-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: starcity
    ports:
      - "5432:5432"
    volumes:
      - starcity_postgres_data:/var/lib/postgresql/data

volumes:
  starcity_postgres_data: